import 'package:flutter/material.dart';
import 'package:kuran_sure_meal_app/widgets/buton.dart';
import 'package:kuran_sure_meal_app/pages/read/readScreen.dart';

class GridGenerator {
  static List<Widget> buttons = [
    Buton(sureAd: "Fatiha", onTap: () => sureView.addSureInput("Fatiha", 1)),
    Buton(sureAd: "Bakara", onTap: () => sureView.addSureInput("Bakara", 2)),
    Buton(
        sureAd: "Al-i İmran",
        onTap: () => sureView.addSureInput("Al-i İmran", 3)),
    Buton(sureAd: "Nisa", onTap: () => sureView.addSureInput("Nisa", 4)),
    Buton(sureAd: "Mâide", onTap: () => sureView.addSureInput("Mâide", 5)),
    Buton(sureAd: "En'am", onTap: () => sureView.addSureInput("En'am", 6)),
    Buton(sureAd: "A'raf", onTap: () => sureView.addSureInput("A'raf", 7)),
    Buton(sureAd: "Enfal", onTap: () => sureView.addSureInput("Enfal", 8)),
    Buton(sureAd: "Tevbe", onTap: () => sureView.addSureInput("Tevbe", 9)),
    Buton(sureAd: "Yunus", onTap: () => sureView.addSureInput("Yunus", 10)),
    Buton(sureAd: "Hûd", onTap: () => sureView.addSureInput("Hûd", 11)),
    Buton(sureAd: "Yusuf", onTap: () => sureView.addSureInput("Yusuf", 12)),
    Buton(sureAd: "Rad", onTap: () => sureView.addSureInput("Rad", 13)),
    Buton(sureAd: "İbrahim", onTap: () => sureView.addSureInput("İbrahim", 14)),
    Buton(sureAd: "Hicr", onTap: () => sureView.addSureInput("Hicr", 15)),
    Buton(sureAd: "Nahl", onTap: () => sureView.addSureInput("Nahl", 16)),
    Buton(sureAd: "İsra", onTap: () => sureView.addSureInput("İsra", 17)),
    Buton(sureAd: "Kehf", onTap: () => sureView.addSureInput("Kehf", 18)),
    Buton(sureAd: "Meryem", onTap: () => sureView.addSureInput("Meryem", 19)),
    Buton(sureAd: "Ta-Ha", onTap: () => sureView.addSureInput("Ta-Ha", 20)),
    Buton(sureAd: "Enbiya", onTap: () => sureView.addSureInput("Enbiya", 21)),
    Buton(sureAd: "Hac", onTap: () => sureView.addSureInput("Hac", 22)),
    Buton(sureAd: "Müminun", onTap: () => sureView.addSureInput("Müminun", 23)),
    Buton(sureAd: "Nur", onTap: () => sureView.addSureInput("Nur", 24)),
    Buton(sureAd: "Furkan", onTap: () => sureView.addSureInput("Furkan", 25)),
    Buton(sureAd: "Şuara", onTap: () => sureView.addSureInput("Şuara", 26)),
    Buton(sureAd: "Neml", onTap: () => sureView.addSureInput("Neml", 27)),
    Buton(sureAd: "Kasas", onTap: () => sureView.addSureInput("Kasas", 28)),
    Buton(sureAd: "Ankebut", onTap: () => sureView.addSureInput("Ankebut", 29)),
    Buton(sureAd: "Rum", onTap: () => sureView.addSureInput("Rum", 30)),
    Buton(sureAd: "Lokman", onTap: () => sureView.addSureInput("Lokman", 31)),
    Buton(sureAd: "Secde", onTap: () => sureView.addSureInput("Secde", 32)),
    Buton(sureAd: "Ahzab", onTap: () => sureView.addSureInput("Ahzab", 33)),
    Buton(sureAd: "Sebe", onTap: () => sureView.addSureInput("Sebe", 34)),
    Buton(sureAd: "Fâtır", onTap: () => sureView.addSureInput("Fâtır", 35)),
    Buton(sureAd: "Ya-Sin", onTap: () => sureView.addSureInput("Ya-Sin", 36)),
    Buton(sureAd: "Saffat", onTap: () => sureView.addSureInput("Saffat", 37)),
    Buton(sureAd: "Sad", onTap: () => sureView.addSureInput("Sad", 38)),
    Buton(sureAd: "Zümer", onTap: () => sureView.addSureInput("Zümer", 39)),
    Buton(sureAd: "Mümin", onTap: () => sureView.addSureInput("Mümin", 40)),
    Buton(
        sureAd: "Fussilet", onTap: () => sureView.addSureInput("Fussilet", 41)),
    Buton(sureAd: "Şura", onTap: () => sureView.addSureInput("Şura", 42)),
    Buton(sureAd: "Zuhruf", onTap: () => sureView.addSureInput("Zuhruf", 43)),
    Buton(sureAd: "Duhan", onTap: () => sureView.addSureInput("Duhan", 44)),
    Buton(sureAd: "Casiye", onTap: () => sureView.addSureInput("Casiye", 45)),
    Buton(sureAd: "Ahkaf", onTap: () => sureView.addSureInput("Ahkaf", 46)),
    Buton(
        sureAd: "Muhammed", onTap: () => sureView.addSureInput("Muhammed", 47)),
    Buton(sureAd: "Fetih", onTap: () => sureView.addSureInput("Fetih", 48)),
    Buton(sureAd: "Hucurat", onTap: () => sureView.addSureInput("Hucurat", 49)),
    Buton(sureAd: "Kaf", onTap: () => sureView.addSureInput("Kaf", 50)),
    Buton(sureAd: "Zariyat", onTap: () => sureView.addSureInput("Zariyat", 51)),
    Buton(sureAd: "Tur", onTap: () => sureView.addSureInput("Tur", 52)),
    Buton(sureAd: "Necm", onTap: () => sureView.addSureInput("Necm", 53)),
    Buton(sureAd: "Kamer", onTap: () => sureView.addSureInput("Kamer", 54)),
    Buton(sureAd: "Rahman", onTap: () => sureView.addSureInput("Rahman", 55)),
    Buton(sureAd: "Vakıa", onTap: () => sureView.addSureInput("Vakıa", 56)),
    Buton(sureAd: "Hadid", onTap: () => sureView.addSureInput("Hadid", 57)),
    Buton(
        sureAd: "Mücadile", onTap: () => sureView.addSureInput("Mücadile", 58)),
    Buton(sureAd: "Haşr", onTap: () => sureView.addSureInput("Haşr", 59)),
    Buton(
        sureAd: "Mümtehine",
        onTap: () => sureView.addSureInput("Mümtehine", 60)),
    Buton(sureAd: "Saf", onTap: () => sureView.addSureInput("Saf", 61)),
    Buton(sureAd: "Cuma", onTap: () => sureView.addSureInput("Cuma", 62)),
    Buton(
        sureAd: "Münafikun",
        onTap: () => sureView.addSureInput("Münafikun", 63)),
    Buton(sureAd: "Tegabun", onTap: () => sureView.addSureInput("Tegabun", 64)),
    Buton(sureAd: "Talak", onTap: () => sureView.addSureInput("Talak", 65)),
    Buton(sureAd: "Tahrim", onTap: () => sureView.addSureInput("Tahrim", 66)),
    Buton(sureAd: "Mülk", onTap: () => sureView.addSureInput("Mülk", 67)),
    Buton(sureAd: "Kalem", onTap: () => sureView.addSureInput("Kalem", 68)),
    Buton(sureAd: "Hakka", onTap: () => sureView.addSureInput("Hakka", 69)),
    Buton(sureAd: "Mearic", onTap: () => sureView.addSureInput("Mearic", 70)),
    Buton(sureAd: "Nuh", onTap: () => sureView.addSureInput("Nuh", 71)),
    Buton(sureAd: "Cin", onTap: () => sureView.addSureInput("Cin", 72)),
    Buton(
        sureAd: "Müzemmil", onTap: () => sureView.addSureInput("Müzemmil", 73)),
    Buton(
        sureAd: "Müdessir", onTap: () => sureView.addSureInput("Müdessir", 74)),
    Buton(sureAd: "Kıyamet", onTap: () => sureView.addSureInput("Kıyamet", 75)),
    Buton(sureAd: "İnsan", onTap: () => sureView.addSureInput("İnsan", 76)),
    Buton(
        sureAd: "Mürselat", onTap: () => sureView.addSureInput("Mürselat", 77)),
    Buton(sureAd: "Nebe", onTap: () => sureView.addSureInput("Nebe", 78)),
    Buton(sureAd: "Naziat", onTap: () => sureView.addSureInput("Naziat", 79)),
    Buton(sureAd: "Abese", onTap: () => sureView.addSureInput("Abese", 80)),
    Buton(sureAd: "Tekvir", onTap: () => sureView.addSureInput("Tekvir", 81)),
    Buton(sureAd: "İnfitar", onTap: () => sureView.addSureInput("İnfitar", 82)),
    Buton(
        sureAd: "Mutafffifin",
        onTap: () => sureView.addSureInput("Mutafffifin", 83)),
    Buton(sureAd: "İnşikak", onTap: () => sureView.addSureInput("İnşikak", 84)),
    Buton(sureAd: "Buruc", onTap: () => sureView.addSureInput("Buruc", 85)),
    Buton(sureAd: "Tarık", onTap: () => sureView.addSureInput("Tarık", 86)),
    Buton(sureAd: "Ala", onTap: () => sureView.addSureInput("Ala", 87)),
    Buton(sureAd: "Gaşiye", onTap: () => sureView.addSureInput("Gaşiye", 88)),
    Buton(sureAd: "Fecir", onTap: () => sureView.addSureInput("Fecir", 89)),
    Buton(sureAd: "Beled", onTap: () => sureView.addSureInput("Beled", 90)),
    Buton(sureAd: "Şems", onTap: () => sureView.addSureInput("Şems", 91)),
    Buton(sureAd: "Leyl", onTap: () => sureView.addSureInput("Leyl", 92)),
    Buton(sureAd: "Duha", onTap: () => sureView.addSureInput("Duha", 93)),
    Buton(sureAd: "İnşirah", onTap: () => sureView.addSureInput("İnşirah", 94)),
    Buton(sureAd: "Tin", onTap: () => sureView.addSureInput("Tin", 95)),
    Buton(sureAd: "Alak", onTap: () => sureView.addSureInput("Alak", 96)),
    Buton(sureAd: "Kadir", onTap: () => sureView.addSureInput("Kadir", 97)),
    Buton(sureAd: "Beyyine", onTap: () => sureView.addSureInput("Beyyine", 98)),
    Buton(sureAd: "Zilzal", onTap: () => sureView.addSureInput("Zilzal", 99)),
    Buton(sureAd: "Adiyat", onTap: () => sureView.addSureInput("Adiyat", 100)),
    Buton(sureAd: "Karia", onTap: () => sureView.addSureInput("Karia", 101)),
    Buton(
        sureAd: "Tekasür", onTap: () => sureView.addSureInput("Tekasür", 102)),
    Buton(sureAd: "Asr", onTap: () => sureView.addSureInput("Asr", 103)),
    Buton(sureAd: "Hümeze", onTap: () => sureView.addSureInput("Hümeze", 104)),
    Buton(sureAd: "Fil", onTap: () => sureView.addSureInput("Fil", 105)),
    Buton(sureAd: "Kureyş", onTap: () => sureView.addSureInput("Kureyş", 106)),
    Buton(sureAd: "Maun", onTap: () => sureView.addSureInput("Maun", 107)),
    Buton(sureAd: "Kevser", onTap: () => sureView.addSureInput("Kevser", 108)),
    Buton(
        sureAd: "Kafirun", onTap: () => sureView.addSureInput("Kafirun", 109)),
    Buton(sureAd: "Nasr", onTap: () => sureView.addSureInput("Nasr", 110)),
    Buton(sureAd: "Mesed", onTap: () => sureView.addSureInput("Mesed", 111)),
    Buton(sureAd: "İhlas", onTap: () => sureView.addSureInput("İhlas", 112)),
    Buton(sureAd: "Felak", onTap: () => sureView.addSureInput("Felak", 113)),
    Buton(sureAd: "Nas", onTap: () => sureView.addSureInput("Nas", 114)),
  ];
}
